version: 2

sources:
  - name: dbt_sleon_dev_dbt_test__audit
    tables:
      - name: accepted_values_stg_tpch_regio_b183f6793b6b9ed291e77a38772a42f8
      - name: not_null_dim_customers_customer_key
      - name: not_null_dim_suppliers_supplier_key
      - name: not_null_fct_order_items_order_item_key
      - name: not_null_fct_orders_order_key
      - name: not_null_my_package_model_id
      - name: not_null_my_second_dbt_model_id
      - name: not_null_order_items_order_item_key
      - name: not_null_part_suppliers_part_supplier_key
      - name: not_null_stg_tpch_customers_customer_key
      - name: not_null_stg_tpch_line_items_order_item_key
      - name: not_null_stg_tpch_nations_nation_key
      - name: not_null_stg_tpch_orders_order_key
      - name: not_null_stg_tpch_part_suppliers_part_supplier_key
      - name: not_null_stg_tpch_parts_part_key
      - name: not_null_stg_tpch_regions_region_key
      - name: not_null_stg_tpch_suppliers_supplier_key
      - name: source_not_null_tpch_customer_c_custkey
      - name: source_not_null_tpch_nation_n_nationkey
      - name: source_not_null_tpch_orders_o_orderkey
      - name: source_not_null_tpch_part_p_partkey
      - name: source_not_null_tpch_region_r_regionkey
      - name: source_not_null_tpch_supplier_s_suppkey
      - name: source_relationships_tpch_line_0403124f3724b4d6984e362cbdf30740
      - name: source_relationships_tpch_line_43b59984a4c7b172d1e95c13fec6bd9c
      - name: source_relationships_tpch_line_56b786676a582f41b4502498079b8292
      - name: source_relationships_tpch_nati_863138f31f617783ad556b879ab65039
      - name: source_relationships_tpch_orde_aa2aa3d71f8f1d2febff342069b4fe2b
      - name: source_relationships_tpch_part_a4c1d3c0d0f0db1ff9c10bf48b8c8fe8
      - name: source_relationships_tpch_part_c5396ae9effd9c1528d06af4f91b3817
      - name: source_relationships_tpch_supp_1c9d96c407a8f937b03dcfc97848e71b
      - name: source_unique_tpch_customer_c_custkey
      - name: source_unique_tpch_nation_n_nationkey
      - name: source_unique_tpch_orders_o_orderkey
      - name: source_unique_tpch_part_p_partkey
      - name: source_unique_tpch_region_r_regionkey
      - name: source_unique_tpch_supplier_s_suppkey
      - name: stg_tpch_orders_assert_positive_price
      - name: test_123
      - name: test_1234
      - name: unique_dim_customers_customer_key
      - name: unique_dim_parts_manufacturer
      - name: unique_dim_parts_part_key
      - name: unique_dim_suppliers_supplier_key
      - name: unique_fct_order_items_order_item_key
      - name: unique_fct_orders_order_key
      - name: unique_my_package_model_id
      - name: unique_my_second_dbt_model_id
      - name: unique_order_items_order_item_key
      - name: unique_part_suppliers_part_supplier_key
      - name: unique_stg_tpch_customers_customer_key
      - name: unique_stg_tpch_line_items_order_item_key
      - name: unique_stg_tpch_nations_nation_key
      - name: unique_stg_tpch_orders_order_key
      - name: unique_stg_tpch_part_suppliers_part_supplier_key
      - name: unique_stg_tpch_parts_part_key
      - name: unique_stg_tpch_regions_region_key
      - name: unique_stg_tpch_suppliers_supplier_key

  - name: dbt_sleon_dev
    tables:
      - name: test_results_central